### ISSUE TITLE
Window 加载 ddtrace 异常

### ISSUE THREAD

**Issue by lrwh** [GuanceCloud/agent-attach-java#11]
## 环境

- Window 11
- JDK"1.8.0_333"

## RUN

**1. 启动应用**

` java  -jar -Dloader.path="lib/" springboot-server2.jar`

**2. 启动 agent**

` java -Xbootclasspath/a:$JAVA_HOME/lib/tools.jar -jar agent-attach-java-jar-with-dependencies.jar  -options "dd.agent.port=9529,dd.trace.debug=true"  -displayName springboot-server2.jar -agent-jar D:/Desktop/target/target/dd-java-agent-1.21.1-guance.jar
`

___

**Exception**

- java.io.FileNotFoundException: JAR entry nst/META-INF/services/datadog.trace.agent.tooling.Instrumenter not found in D:\Desktop\target\target\dd-java-agent-1.21.1-guance.jar
- java.io.FileNotFoundException: JAR entry nst/known-types.index not found in D:\Desktop\target\target\dd-java-agent-1.21.1-guance.jar

**应用日志**

```log
2023-12-12 16:14:51.226 [main] INFO  c.z.o.s.ServerApplication - [logStarted,57] [traceId= spanId=] - Started ServerApplication in 3.837 seconds (JVM running for 4.407)
....................
1.21.1-guance~cd83f12e1b
set dd.agent.port = 9529
set dd.trace.debug = true
[dd.trace 2023-12-12 16:15:00:153 +0800] [Attach Listener] ERROR datadog.trace.agent.tooling.Instrumenters - Failed to load - instrumentation.class list
java.io.FileNotFoundException: JAR entry nst/META-INF/services/datadog.trace.agent.tooling.Instrumenter not found in D:\Desktop\target\target\dd-java-agent-1.21.1-guance.jar
        at org.springframework.boot.loader.jar.JarURLConnection.throwFileNotFound(JarURLConnection.java:129)
        at org.springframework.boot.loader.jar.JarURLConnection.connect(JarURLConnection.java:117)
        at org.springframework.boot.loader.jar.JarURLConnection.getInputStream(JarURLConnection.java:185)
        at java.net.URL.openStream(URL.java:1092)
        at datadog.trace.agent.tooling.Instrumenters.loadInstrumenterNames(Instrumenters.java:105)
        at datadog.trace.agent.tooling.Instrumenters.load(Instrumenters.java:32)
        at datadog.trace.agent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:146)
        at datadog.trace.agent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:69)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at datadog.trace.bootstrap.Agent.startDatadogAgent(Agent.java:543)
        at datadog.trace.bootstrap.Agent.start(Agent.java:243)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at datadog.trace.bootstrap.AgentBootstrap.agentmain(AgentBootstrap.java:86)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)
[dd.trace 2023-12-12 16:15:00:163 +0800] [Attach Listener] DEBUG datadog.trace.agent.tooling.AgentInstaller - Installed 0 instrumenter(s)
[dd.trace 2023-12-12 16:15:00:165 +0800] [Attach Listener] ERROR datadog.trace.agent.tooling.KnownTypesIndex - Problem reading known-types.index
java.io.FileNotFoundException: JAR entry nst/known-types.index not found in D:\Desktop\target\target\dd-java-agent-1.21.1-guance.jar
        at org.springframework.boot.loader.jar.JarURLConnection.throwFileNotFound(JarURLConnection.java:129)
        at org.springframework.boot.loader.jar.JarURLConnection.connect(JarURLConnection.java:117)
        at org.springframework.boot.loader.jar.JarURLConnection.getInputStream(JarURLConnection.java:185)
        at java.net.URL.openStream(URL.java:1092)
        at datadog.trace.agent.tooling.KnownTypesIndex.readIndex(KnownTypesIndex.java:60)
        at datadog.trace.agent.tooling.CombiningMatcher.<clinit>(CombiningMatcher.java:26)
        at datadog.trace.agent.tooling.CombiningTransformerBuilder.installOn(CombiningTransformerBuilder.java:194)
        at datadog.trace.agent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:210)
        at datadog.trace.agent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:69)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at datadog.trace.bootstrap.Agent.startDatadogAgent(Agent.java:543)
        at datadog.trace.bootstrap.Agent.start(Agent.java:243)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at datadog.trace.bootstrap.AgentBootstrap.agentmain(AgentBootstrap.java:86)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)
[dd.trace 2023-12-12 16:15:00:168 +0800] [Attach Listener] DEBUG datadog.trace.agent.tooling.KnownTypesIndex - Generating KnownTypesIndex

[dd.trace 2023-12-12 16:15:00:257 +0800] [Attach Listener] DEBUG datadog.trace.agent.tooling.AgentInstaller - Instrumentation installed for [TRACING, APPSEC]
[dd.trace 2023-12-12 16:15:00:285 +0800] [Attach Listener] DEBUG datadog.trace.api.Config - Determined hostname from environment variable
[dd.trace 2023-12-12 16:15:00:285 +0800] [Attach Listener] DEBUG datadog.trace.api.Config - New instance: Config{instrumenterConfig=InstrumenterConfig{integrationsEnabled=true, traceEnabled=true, traceOtelEnabled=false, logs128bTraceIdEnabled=false, profilingEnabled=false, ciVisibilityEnabled=false, appSecActivation=ENABLED_INACTIVE, iastActivation=FULLY_DISABLED, usmEnabled=false, telemetryEnabled=true, traceExecutorsAll=false, traceExecutors=[], jdbcPreparedStatementClassName='', jdbcConnectionClassName='', excludedClasses=[], excludedClassesFile=null, excludedClassLoaders=[], excludedCodeSources=[], resolverCacheConfig=MEMOS, resolverCacheDir=null, resolverNamesAreUnique=false, resolverUseLoadClass=true, resolverUseUrlCaches=null, resolverResetInterval=300, runtimeContextFieldInjection=true, serialVersionUIDFieldInjection=true, traceAnnotations='null', traceAnnotationAsync=false, traceMethods='{}', measureMethods= '{}', internalExitOnFailure=false, legacyInstallerEnabled=false}, runtimeId='12f34dfd-9468-4bf5-80bc-2925ce10c0de', runtimeVersion='1.8.0_333, apiKey=null, site='datadoghq.com', hostName='DESKTOP-3JJLRI8', serviceName='springboot-server2', serviceNameSetByUser=false, rootContextServiceName=root-servlet, integrationSynapseLegacyOperationName=false, writerType='DDAgentWriter', agentConfiguredUsingDefault=false, agentUrl='http://localhost:9529', agentHost='localhost', agentPort=9529, agentUnixDomainSocket='null', agentTimeout=10, noProxyHosts=[], prioritySamplingEnabled=true, prioritySamplingForce='null', traceResolverEnabled=true, serviceMapping={}, tags={}, spanTags={}, jmxTags={}, requestHeaderTags={}, responseHeaderTags={}, baggageMapping={}, httpServerErrorStatuses={500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599}, httpClientErrorStatuses={400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499}, httpServerTagQueryString=true, httpServerRawQueryString=true, httpServerRawResource=false, httpServerRouteBasedNaming=true, httpServerPathResourceNameMapping={}, httpClientPathResourceNameMapping={}, httpClientTagQueryString=false, httpClientSplitByDomain=false, httpResourceRemoveTrailingSlashfalse, dbClientSplitByInstance=false, dbClientSplitByInstanceTypeSuffix=false, DBMPropagationMode=disabled, splitByTags=[], scopeDepthLimit=100, scopeStrictMode=false, scopeInheritAsyncPropagation=true, scopeIterationKeepAlive=30, partialFlushMinSpans=1000, traceStrictWritesEnabled=false, tracePropagationStylesToExtract=[datadog], tracePropagationStylesToInject=[datadog], clockSyncPeriod=30, jmxFetchEnabled=true, dogStatsDStartDelay=15, jmxFetchConfigDir='null', jmxFetchConfigs=[], jmxFetchMetricsConfigs=[], jmxFetchCheckPeriod=null, jmxFetchInitialRefreshBeansPeriod=null, jmxFetchRefreshBeansPeriod=null, jmxFetchStatsdHost='null', jmxFetchStatsdPort=null, jmxFetchMultipleRuntimeServicesEnabled=false, jmxFetchMultipleRuntimeServicesLimit=10, healthMetricsEnabled=true, healthMetricsStatsdHost='null', healthMetricsStatsdPort=null, perfMetricsEnabled=false, tracerMetricsEnabled=false, tracerMetricsBufferingEnabled=false, tracerMetricsMaxAggregates=2048, tracerMetricsMaxPending=2048, logsInjectionEnabled=true, logsMDCTagsInjectionEnabled=true, logPattern=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger - [%method,%line] %X{dd.service} %X{dd.trace_id} %X{dd.span_id} - %msg%n, logPatternReplace=false, reportHostName=false, traceAnalyticsEnabled=false, traceSamplingServiceRules={}, traceSamplingOperationRules={}, traceSamplingJsonRules=null, traceSampleRate=null, traceRateLimit=100, spanSamplingRules=null, spanSamplingRulesFile=null, profilingAgentless=false, profilingUrl='null', profilingTags={}, profilingStartDelay=10, profilingStartForceFirst=false, profilingUploadPeriod=60, profilingTemplateOverrideFile='null', profilingUploadTimeout=30, profilingUploadCompression='on', profilingProxyHost='null', profilingProxyPort=8080, profilingProxyUsername='null', profilingProxyPassword=null, profilingExceptionSampleLimit=10000, profilingExceptionHistogramTopItems=50, profilingExceptionHistogramMaxCollectionSize=10000, profilingExcludeAgentThreads=true, crashTrackingTags={}, crashTrackingAgentless=false, remoteConfigEnabled=true, remoteConfigUrl=null, remoteConfigPollIntervalSeconds=5.0, remoteConfigMaxPayloadSize=5242880, remoteConfigIntegrityCheckEnabled=false, debuggerEnabled=false, debuggerUploadTimeout=30, debuggerUploadFlushInterval=0, debuggerClassFileDumpEnabled=false, debuggerPollInterval=1, debuggerDiagnosticsInterval=3600, debuggerMetricEnabled=true, debuggerProbeFileLocation=null, debuggerUploadBatchSize=100, debuggerMaxPayloadSize=1048576, debuggerVerifyByteCode=true, debuggerInstrumentTheWorld=false, debuggerExcludeFile=null, awsPropagationEnabled=true, sqsPropagationEnabled=true, kafkaClientPropagationEnabled=true, kafkaClientPropagationDisabledTopics=[], kafkaClientBase64DecodingEnabled=false, jmsPropagationEnabled=true, jmsPropagationDisabledTopics=[], jmsPropagationDisabledQueues=[], rabbitPropagationEnabled=true, rabbitPropagationDisabledQueues=[], rabbitPropagationDisabledExchanges=[], messageBrokerSplitByDestination=false, hystrixTagsEnabled=false, hystrixMeasuredEnabled=false, igniteCacheIncludeKeys=false, servletPrincipalEnabled=false, servletAsyncTimeoutError=true, datadogTagsLimit=512, traceAgentV05Enabled=false, debugEnabled=true, startLogsEnabled=true, configFile='no config file present', idGenerationStrategy=datadog.trace.api.IdGenerationStrategy$Random@41e352fa, trace128bitTraceIdGenerationEnabledfalse, grpcIgnoredInboundMethods=[], grpcIgnoredOutboundMethods=[], grpcServerErrorStatuses={2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}, grpcClientErrorStatuses={1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}, clientIpEnabled=false, appSecReportingInband=false, appSecRulesFile='null', appSecHttpBlockedTemplateHtml=null, appSecWafTimeout=100000 us, appSecHttpBlockedTemplateJson=null, cwsEnabled=false, cwsTlsRefresh=5000, longRunningTraceEnabled=false, longRunningTraceFlushInterval=300, elasticsearchBodyEnabled=false, elasticsearchParamsEnabled=true, elasticsearchBodyAndParamsEnabled=false, traceFlushInterval=1.0, injectBaggageAsTagsEnabled=true, logsInjectionEnabled=true, sparkTaskHistogramEnabled=true, jaxRsExceptionAsErrorsEnabled=true, peerServiceDefaultsEnabled=false, peerServiceComponentOverrides={}, removeIntegrationServiceNamesEnabled=false, spanAttributeSchemaVersion=0}
[dd.trace 2023-12-12 16:15:00:316 +0800] [Attach Listener] DEBUG datadog.communication.monitor.DDAgentStatsDConnection - Scheduling StatsD connection in 15 seconds - <auto-detect>

```

**Comment by lrwh** [comment]
agent-attach-java 需要按照以下方式操作解决问题：

- JDK1.8
- window

需要在以上环境上进行编译才会正常运行。
