### ISSUE TITLE
本地编译运行报错

### ISSUE THREAD

**Issue by songlonqi-java** [GuanceCloud/agent-attach-java#6]
报错信息：
```txt
[root@APPServer javaapp]# java -jar  agent-attach-java-jar-with-dependencies.jar -options "dd.agent.port=9529" > error.log
java.util.ServiceConfigurationError: com.sun.tools.attach.spi.AttachProvider: Provider io.earcam.wrapped.com.sun.tools.attach.Provider could not be instantiated
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
        at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:804)
        at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:722)
        at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1395)
        at jdk.attach/com.sun.tools.attach.spi.AttachProvider.providers(AttachProvider.java:260)
        at jdk.attach/com.sun.tools.attach.VirtualMachine.list(VirtualMachine.java:144)
        at com.guance.javaagent.JavaAgentLoader.loadAgent(JavaAgentLoader.java:20)
        at com.guance.javaagent.MyMainClass.main(MyMainClass.java:20)
Caused by: java.lang.NoClassDefFoundError: sun/tools/attach/WindowsAttachProvider
        at io.earcam.wrapped.com.sun.tools.attach.Provider.findProvider(Provider.java:33)
        at io.earcam.wrapped.com.sun.tools.attach.Provider.<init>(Provider.java:25)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:780)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: sun.tools.attach.WindowsAttachProvider
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 13 more

Exception in thread "main" java.lang.RuntimeException: java.io.IOException: Can not attach to current VM
        at com.guance.javaagent.JavaAgentLoader.loadAgent(JavaAgentLoader.java:34)
        at com.guance.javaagent.MyMainClass.main(MyMainClass.java:20)
Caused by: java.io.IOException: Can not attach to current VM
        at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.<init>(HotSpotVirtualMachine.java:75)
        at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(VirtualMachineImpl.java:57)
        at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:58)
        at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
        at com.guance.javaagent.JavaAgentLoader.loadAgent(JavaAgentLoader.java:24)
        ... 1 more
```

环境： JDK 11.0.15

**Comment by songlonqi-java** [comment]
相近问题 https://stackoverflow.com/questions/45940297/java-lang-classnotfoundexception-error-when-trying-to-inject-into-running-vm

**Comment by songlonqi-java** [comment]
将 tools.jar 放到lib中。在运行 就不会报错。

版本 v0.4 以上已经修复这个错误
